name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7'
      - run: bundle
      - run: bundle exec rspec

